<?php
echo "		<nav class=\"navbar navbar-inverse navbar-fixed-top\">\n";
echo "		<div class=\"container-fluid\">\n";
echo "			<div class=\"navbar-header\">\n";
echo "			<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\n";
echo "			<span class=\"icon-bar\"></span>\n";
echo "			<span class=\"icon-bar\"></span>\n";
echo "			<span class=\"icon-bar\"></span>\n";
echo "			</button>\n";
echo "			<a class=\"navbar-brand\" href=\"#\">TeamCDA</a>\n";
echo "			</div>\n";
echo "			<div class=\"collapse navbar-collapse\" id=\"myNavbar\">\n";
echo "				<ul class=\"nav navbar-nav\">\n";
echo "				<li class=\"active\"><a href=\"#\" onclick=\"HomePage()\">Home</a></li>\n";
echo "				<li class=\"dropdown\"><a href=\"#\" onclick=\"AboutPage()\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">About<span class=\"caret\"></span></a>\n";
echo "				<ul class=\"dropdown-menu\">\n";
echo "				<li><a href=\"#\" onclick=\"ContactPage()\">Contact Us</a></li>\n";
echo "				</ul>\n";
echo "				</li>\n";
echo "				<li><a href=\"#\" onclick=\"NewsPage()\">News</a></li>\n";
echo "				<li class=\"dropdown\"><a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">Games<span class=\"caret\"></span></a>\n";
echo "				<ul class=\"dropdown-menu\">\n";
echo "				<li><a href=\"#\" onclick=\"HappyWheels()\">Happy Wheels</a></li>\n";
echo "				</ul>\n";
echo "				</li>\n";
echo "				</ul>\n";
echo "			</div>\n";
echo "		</div>\n";
echo "		</nav>";
?>
